# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/pfile/web4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/pfile/web4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pfile/web4/CMakeFiles /Users/pfile/web4/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pfile/web4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named webserv

# Build rule for target.
webserv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 webserv
.PHONY : webserv

# fast build rule for target.
webserv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/build
.PHONY : webserv/fast

serverf/main.o: serverf/main.cpp.o

.PHONY : serverf/main.o

# target to build an object file
serverf/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/serverf/main.cpp.o
.PHONY : serverf/main.cpp.o

serverf/main.i: serverf/main.cpp.i

.PHONY : serverf/main.i

# target to preprocess a source file
serverf/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/serverf/main.cpp.i
.PHONY : serverf/main.cpp.i

serverf/main.s: serverf/main.cpp.s

.PHONY : serverf/main.s

# target to generate assembly for a file
serverf/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/serverf/main.cpp.s
.PHONY : serverf/main.cpp.s

source/config.o: source/config.cpp.o

.PHONY : source/config.o

# target to build an object file
source/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config.cpp.o
.PHONY : source/config.cpp.o

source/config.i: source/config.cpp.i

.PHONY : source/config.i

# target to preprocess a source file
source/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config.cpp.i
.PHONY : source/config.cpp.i

source/config.s: source/config.cpp.s

.PHONY : source/config.s

# target to generate assembly for a file
source/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config.cpp.s
.PHONY : source/config.cpp.s

source/config/Interpreter.o: source/config/Interpreter.cpp.o

.PHONY : source/config/Interpreter.o

# target to build an object file
source/config/Interpreter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Interpreter.cpp.o
.PHONY : source/config/Interpreter.cpp.o

source/config/Interpreter.i: source/config/Interpreter.cpp.i

.PHONY : source/config/Interpreter.i

# target to preprocess a source file
source/config/Interpreter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Interpreter.cpp.i
.PHONY : source/config/Interpreter.cpp.i

source/config/Interpreter.s: source/config/Interpreter.cpp.s

.PHONY : source/config/Interpreter.s

# target to generate assembly for a file
source/config/Interpreter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Interpreter.cpp.s
.PHONY : source/config/Interpreter.cpp.s

source/config/Lexer.o: source/config/Lexer.cpp.o

.PHONY : source/config/Lexer.o

# target to build an object file
source/config/Lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Lexer.cpp.o
.PHONY : source/config/Lexer.cpp.o

source/config/Lexer.i: source/config/Lexer.cpp.i

.PHONY : source/config/Lexer.i

# target to preprocess a source file
source/config/Lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Lexer.cpp.i
.PHONY : source/config/Lexer.cpp.i

source/config/Lexer.s: source/config/Lexer.cpp.s

.PHONY : source/config/Lexer.s

# target to generate assembly for a file
source/config/Lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Lexer.cpp.s
.PHONY : source/config/Lexer.cpp.s

source/config/Node.o: source/config/Node.cpp.o

.PHONY : source/config/Node.o

# target to build an object file
source/config/Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Node.cpp.o
.PHONY : source/config/Node.cpp.o

source/config/Node.i: source/config/Node.cpp.i

.PHONY : source/config/Node.i

# target to preprocess a source file
source/config/Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Node.cpp.i
.PHONY : source/config/Node.cpp.i

source/config/Node.s: source/config/Node.cpp.s

.PHONY : source/config/Node.s

# target to generate assembly for a file
source/config/Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Node.cpp.s
.PHONY : source/config/Node.cpp.s

source/config/ParseResult.o: source/config/ParseResult.cpp.o

.PHONY : source/config/ParseResult.o

# target to build an object file
source/config/ParseResult.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/ParseResult.cpp.o
.PHONY : source/config/ParseResult.cpp.o

source/config/ParseResult.i: source/config/ParseResult.cpp.i

.PHONY : source/config/ParseResult.i

# target to preprocess a source file
source/config/ParseResult.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/ParseResult.cpp.i
.PHONY : source/config/ParseResult.cpp.i

source/config/ParseResult.s: source/config/ParseResult.cpp.s

.PHONY : source/config/ParseResult.s

# target to generate assembly for a file
source/config/ParseResult.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/ParseResult.cpp.s
.PHONY : source/config/ParseResult.cpp.s

source/config/Parser.o: source/config/Parser.cpp.o

.PHONY : source/config/Parser.o

# target to build an object file
source/config/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Parser.cpp.o
.PHONY : source/config/Parser.cpp.o

source/config/Parser.i: source/config/Parser.cpp.i

.PHONY : source/config/Parser.i

# target to preprocess a source file
source/config/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Parser.cpp.i
.PHONY : source/config/Parser.cpp.i

source/config/Parser.s: source/config/Parser.cpp.s

.PHONY : source/config/Parser.s

# target to generate assembly for a file
source/config/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Parser.cpp.s
.PHONY : source/config/Parser.cpp.s

source/config/Position.o: source/config/Position.cpp.o

.PHONY : source/config/Position.o

# target to build an object file
source/config/Position.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Position.cpp.o
.PHONY : source/config/Position.cpp.o

source/config/Position.i: source/config/Position.cpp.i

.PHONY : source/config/Position.i

# target to preprocess a source file
source/config/Position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Position.cpp.i
.PHONY : source/config/Position.cpp.i

source/config/Position.s: source/config/Position.cpp.s

.PHONY : source/config/Position.s

# target to generate assembly for a file
source/config/Position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Position.cpp.s
.PHONY : source/config/Position.cpp.s

source/config/Token.o: source/config/Token.cpp.o

.PHONY : source/config/Token.o

# target to build an object file
source/config/Token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Token.cpp.o
.PHONY : source/config/Token.cpp.o

source/config/Token.i: source/config/Token.cpp.i

.PHONY : source/config/Token.i

# target to preprocess a source file
source/config/Token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Token.cpp.i
.PHONY : source/config/Token.cpp.i

source/config/Token.s: source/config/Token.cpp.s

.PHONY : source/config/Token.s

# target to generate assembly for a file
source/config/Token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/Token.cpp.s
.PHONY : source/config/Token.cpp.s

source/config/parse.o: source/config/parse.cpp.o

.PHONY : source/config/parse.o

# target to build an object file
source/config/parse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/parse.cpp.o
.PHONY : source/config/parse.cpp.o

source/config/parse.i: source/config/parse.cpp.i

.PHONY : source/config/parse.i

# target to preprocess a source file
source/config/parse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/parse.cpp.i
.PHONY : source/config/parse.cpp.i

source/config/parse.s: source/config/parse.cpp.s

.PHONY : source/config/parse.s

# target to generate assembly for a file
source/config/parse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/config/parse.cpp.s
.PHONY : source/config/parse.cpp.s

source/default_config.o: source/default_config.cpp.o

.PHONY : source/default_config.o

# target to build an object file
source/default_config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/default_config.cpp.o
.PHONY : source/default_config.cpp.o

source/default_config.i: source/default_config.cpp.i

.PHONY : source/default_config.i

# target to preprocess a source file
source/default_config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/default_config.cpp.i
.PHONY : source/default_config.cpp.i

source/default_config.s: source/default_config.cpp.s

.PHONY : source/default_config.s

# target to generate assembly for a file
source/default_config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/default_config.cpp.s
.PHONY : source/default_config.cpp.s

source/error.o: source/error.cpp.o

.PHONY : source/error.o

# target to build an object file
source/error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/error.cpp.o
.PHONY : source/error.cpp.o

source/error.i: source/error.cpp.i

.PHONY : source/error.i

# target to preprocess a source file
source/error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/error.cpp.i
.PHONY : source/error.cpp.i

source/error.s: source/error.cpp.s

.PHONY : source/error.s

# target to generate assembly for a file
source/error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/error.cpp.s
.PHONY : source/error.cpp.s

source/find.o: source/find.cpp.o

.PHONY : source/find.o

# target to build an object file
source/find.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/find.cpp.o
.PHONY : source/find.cpp.o

source/find.i: source/find.cpp.i

.PHONY : source/find.i

# target to preprocess a source file
source/find.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/find.cpp.i
.PHONY : source/find.cpp.i

source/find.s: source/find.cpp.s

.PHONY : source/find.s

# target to generate assembly for a file
source/find.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/find.cpp.s
.PHONY : source/find.cpp.s

source/header.o: source/header.cpp.o

.PHONY : source/header.o

# target to build an object file
source/header.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/header.cpp.o
.PHONY : source/header.cpp.o

source/header.i: source/header.cpp.i

.PHONY : source/header.i

# target to preprocess a source file
source/header.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/header.cpp.i
.PHONY : source/header.cpp.i

source/header.s: source/header.cpp.s

.PHONY : source/header.s

# target to generate assembly for a file
source/header.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/header.cpp.s
.PHONY : source/header.cpp.s

source/init.o: source/init.cpp.o

.PHONY : source/init.o

# target to build an object file
source/init.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/init.cpp.o
.PHONY : source/init.cpp.o

source/init.i: source/init.cpp.i

.PHONY : source/init.i

# target to preprocess a source file
source/init.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/init.cpp.i
.PHONY : source/init.cpp.i

source/init.s: source/init.cpp.s

.PHONY : source/init.s

# target to generate assembly for a file
source/init.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/init.cpp.s
.PHONY : source/init.cpp.s

source/loop.o: source/loop.cpp.o

.PHONY : source/loop.o

# target to build an object file
source/loop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/loop.cpp.o
.PHONY : source/loop.cpp.o

source/loop.i: source/loop.cpp.i

.PHONY : source/loop.i

# target to preprocess a source file
source/loop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/loop.cpp.i
.PHONY : source/loop.cpp.i

source/loop.s: source/loop.cpp.s

.PHONY : source/loop.s

# target to generate assembly for a file
source/loop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/loop.cpp.s
.PHONY : source/loop.cpp.s

source/route.o: source/route.cpp.o

.PHONY : source/route.o

# target to build an object file
source/route.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/route.cpp.o
.PHONY : source/route.cpp.o

source/route.i: source/route.cpp.i

.PHONY : source/route.i

# target to preprocess a source file
source/route.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/route.cpp.i
.PHONY : source/route.cpp.i

source/route.s: source/route.cpp.s

.PHONY : source/route.s

# target to generate assembly for a file
source/route.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/route.cpp.s
.PHONY : source/route.cpp.s

source/server.o: source/server.cpp.o

.PHONY : source/server.o

# target to build an object file
source/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/server.cpp.o
.PHONY : source/server.cpp.o

source/server.i: source/server.cpp.i

.PHONY : source/server.i

# target to preprocess a source file
source/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/server.cpp.i
.PHONY : source/server.cpp.i

source/server.s: source/server.cpp.s

.PHONY : source/server.s

# target to generate assembly for a file
source/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/server.cpp.s
.PHONY : source/server.cpp.s

source/tests.o: source/tests.cpp.o

.PHONY : source/tests.o

# target to build an object file
source/tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/tests.cpp.o
.PHONY : source/tests.cpp.o

source/tests.i: source/tests.cpp.i

.PHONY : source/tests.i

# target to preprocess a source file
source/tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/tests.cpp.i
.PHONY : source/tests.cpp.i

source/tests.s: source/tests.cpp.s

.PHONY : source/tests.s

# target to generate assembly for a file
source/tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/source/tests.cpp.s
.PHONY : source/tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... webserv"
	@echo "... serverf/main.o"
	@echo "... serverf/main.i"
	@echo "... serverf/main.s"
	@echo "... source/config.o"
	@echo "... source/config.i"
	@echo "... source/config.s"
	@echo "... source/config/Interpreter.o"
	@echo "... source/config/Interpreter.i"
	@echo "... source/config/Interpreter.s"
	@echo "... source/config/Lexer.o"
	@echo "... source/config/Lexer.i"
	@echo "... source/config/Lexer.s"
	@echo "... source/config/Node.o"
	@echo "... source/config/Node.i"
	@echo "... source/config/Node.s"
	@echo "... source/config/ParseResult.o"
	@echo "... source/config/ParseResult.i"
	@echo "... source/config/ParseResult.s"
	@echo "... source/config/Parser.o"
	@echo "... source/config/Parser.i"
	@echo "... source/config/Parser.s"
	@echo "... source/config/Position.o"
	@echo "... source/config/Position.i"
	@echo "... source/config/Position.s"
	@echo "... source/config/Token.o"
	@echo "... source/config/Token.i"
	@echo "... source/config/Token.s"
	@echo "... source/config/parse.o"
	@echo "... source/config/parse.i"
	@echo "... source/config/parse.s"
	@echo "... source/default_config.o"
	@echo "... source/default_config.i"
	@echo "... source/default_config.s"
	@echo "... source/error.o"
	@echo "... source/error.i"
	@echo "... source/error.s"
	@echo "... source/find.o"
	@echo "... source/find.i"
	@echo "... source/find.s"
	@echo "... source/header.o"
	@echo "... source/header.i"
	@echo "... source/header.s"
	@echo "... source/init.o"
	@echo "... source/init.i"
	@echo "... source/init.s"
	@echo "... source/loop.o"
	@echo "... source/loop.i"
	@echo "... source/loop.s"
	@echo "... source/route.o"
	@echo "... source/route.i"
	@echo "... source/route.s"
	@echo "... source/server.o"
	@echo "... source/server.i"
	@echo "... source/server.s"
	@echo "... source/tests.o"
	@echo "... source/tests.i"
	@echo "... source/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

